# Название workflow
name: Deploy Nuxt.js App to GitHub Pages

# Триггеры для запуска workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Задачи workflow
jobs:

  # Задача для сборки проекта
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build Nuxt.js app
        run: yarn build

      - name: Prepare deployment directory
        run: |
          rm -rf .output
          mkdir -p .output/public
          cp -r dist/* .output/public
          touch .output/public/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .output/public

  # Задача для деплоя на GitHub Pages
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          deployment_source: artifact  # Используем артефакт, загруженный на предыдущем шаге
      - run: gh-pages -d dist -t true  # Деплой на GitHub Pages с использованием gh-pages